# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Install dependencies for building
RUN apk add --no-cache git python3 g++ make

WORKDIR /app

# Copy package files and install deps
COPY package.json package-lock.json tsconfig.json ./

# Copy source
COPY cli.js index.js lib? ./
COPY src ./src
COPY utils ./utils
COPY tests ./tests

# Install dependencies and build
RUN npm ci && npm run build

# Default entrypoint for MCP over stdio
ENTRYPOINT ["node", "cli.js"]
